### ISSUE TITLE
Compilation does not work on Win64

### ISSUE THREAD

**Issue by crohr88** [meshkit/cgns4m#1]
Compilation fails at HDF5 download due to changed folder structure at web address
Also recommend using websave with fixed link rather than urlwrite which always fails.

**Comment by crohr88** [comment]
Compilation fails on windows using mingw:

Error using build_mexcgns (line 156)
Error during compilation with err Error using mex
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5T_IEEE_F64LE_g[.refptr.H5T_IEEE_F64LE_g]+0x0):
undefined reference to `H5T_IEEE_F64LE_g'
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5T_IEEE_F64BE_g[.refptr.H5T_IEEE_F64BE_g]+0x0):
undefined reference to `H5T_IEEE_F64BE_g'
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5T_IEEE_F32LE_g[.refptr.H5T_IEEE_F32LE_g]+0x0):
undefined reference to `H5T_IEEE_F32LE_g'
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5T_IEEE_F32BE_g[.refptr.H5T_IEEE_F32BE_g]+0x0):
undefined reference to `H5T_IEEE_F32BE_g'
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5P_CLS_DATASET_CREATE_ID_g[.refptr.H5P_CLS_DATASET_CREATE_ID_g]+0x0):
undefined reference to `H5P_CLS_DATASET_CREATE_ID_g'
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5P_CLS_GROUP_CREATE_ID_g[.refptr.H5P_CLS_GROUP_CREATE_ID_g]+0x0):
undefined reference to `H5P_CLS_GROUP_CREATE_ID_g'
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5P_CLS_LINK_ACCESS_ID_g[.refptr.H5P_CLS_LINK_ACCESS_ID_g]+0x0):
undefined reference to `H5P_CLS_LINK_ACCESS_ID_g'
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5P_CLS_FILE_CREATE_ID_g[.refptr.H5P_CLS_FILE_CREATE_ID_g]+0x0):
undefined reference to `H5P_CLS_FILE_CREATE_ID_g'
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5P_CLS_FILE_ACCESS_ID_g[.refptr.H5P_CLS_FILE_ACCESS_ID_g]+0x0):
undefined reference to `H5P_CLS_FILE_ACCESS_ID_g'
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5T_NATIVE_DOUBLE_g[.refptr.H5T_NATIVE_DOUBLE_g]+0x0):
undefined reference to `H5T_NATIVE_DOUBLE_g'
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5T_NATIVE_FLOAT_g[.refptr.H5T_NATIVE_FLOAT_g]+0x0):
undefined reference to `H5T_NATIVE_FLOAT_g'
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5T_NATIVE_UINT64_g[.refptr.H5T_NATIVE_UINT64_g]+0x0):
undefined reference to `H5T_NATIVE_UINT64_g'
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5T_NATIVE_UINT32_g[.refptr.H5T_NATIVE_UINT32_g]+0x0):
undefined reference to `H5T_NATIVE_UINT32_g'
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5T_NATIVE_INT64_g[.refptr.H5T_NATIVE_INT64_g]+0x0):
undefined reference to `H5T_NATIVE_INT64_g'
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5T_NATIVE_INT32_g[.refptr.H5T_NATIVE_INT32_g]+0x0):
undefined reference to `H5T_NATIVE_INT32_g'
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5T_NATIVE_UCHAR_g[.refptr.H5T_NATIVE_UCHAR_g]+0x0):
undefined reference to `H5T_NATIVE_UCHAR_g'
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5T_NATIVE_SCHAR_g[.refptr.H5T_NATIVE_SCHAR_g]+0x0):
undefined reference to `H5T_NATIVE_SCHAR_g'
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5T_NATIVE_INT_g[.refptr.H5T_NATIVE_INT_g]+0x0):
undefined reference to `H5T_NATIVE_INT_g'
C:\Users\crohr\AppData\Local\Temp\2\mex_1980838298306844_4004\ADFH.obj:ADFH.c:(.rdata$.refptr.H5T_C_S1_g[.refptr.H5T_C_S1_g]+0x0):
undefined reference to `H5T_C_S1_g'
collect2.exe: error: ld returned 1 exit status
.

**Comment by xmjiao** [comment]
Now provide a binary release of CGNS4m for MATLAB with cgnslib v3.4.1 and HDF5 1.8.12.

**Comment by xmjiao** [comment]
Now provide a binary release of CGNS4m for MATLAB with cgnslib v3.4.1 and HDF5 1.8.12.
