### ISSUE TITLE
Error Downloading URL...

### ISSUE THREAD

**Issue by minamoh** [meshkit/cgns4m#2]
Hi

When I run the startup_mexcgns script in Matlab on Microsoft Windows, I get the following errors. I was wondering if you could help me with it. Thanks.
<img width="676" alt="matlab error" src="https://user-images.githubusercontent.com/38486854/38914295-a9d283c2-4293-11e8-885f-4f2d12f63a53.png">

**Comment by xmjiao** [comment]
Now provide a binary release of CGNS4m for MATLAB with cgnslib v3.4.1 and HDF5 1.8.12.
