### ISSUE TITLE
Octave install incorrectly tries to download HDF5

### ISSUE THREAD

**Issue by jtipton2** [meshkit/cgns4m#3]
If I understand correctly, Octave already has HDF5 support built-in.  The current version of **build_cgns5m**, line 46, first tests **ispc**.  This returns true regardless of the octave installation.  The workaround for me was to manually set **if 0%ispc** which then moved to the next conditional test to proceed with the install.

**Comment by xmjiao** [comment]
Thanks for the bug report! I moved the checking of `isoctave` before `ispc`.
